beats:
  - detection_rules/beats.py
  - etc/beats_schemas/**/*
  
documentation:
  - ./**/*.md
  
"Domain: Cloud":
  - any: ['rules/aws/**/*.toml', 'rules/azure/**/*.toml', 'rules/gcp/**/*.toml', 'rules/google-workspace/**/*.toml', 'rules/microsoft-365/**/*.toml', 'rules/okta/**/*.toml']
  
"Domain: Endpoint":
  - any: ['rules/windows/**/*.toml', 'rules/linux/**/*.toml', 'rules/macos/**/*.toml']
  
ecs:
  - detection_rules/ecs.py
  - etc/ecs_schemas/**/*
  
ML:
  - rules/ml/**/*
  
"OS: Linux":
  - rules/linux/**/*.toml

"OS: macOS":
  - rules/macos/**/*.toml

"OS: Windows":
  - rules/windows/**/*.toml
  
"Platform: AWS":
  - rules/aws/**/*.toml
  
"Platform: Azure":
  - rules/azure/**/*.toml

"Platform: GCP":
  - rules/gcp/**/*.toml
  
"Platform: Google Workspace":
  - rules/google-workspace/**/*.toml
  
"Platform: Microsoft 365":
  - rules/microsoft-365/**/*.toml
  
"Platform: Okta":
  - rules/okta/**/*.toml

python:
  - detection_rules/**/*.py
  
RTA:
  - rta/**/*
  
"Rule: Deprecation":
  - rules/_deprecated/**/*

# tests
test-suite:
  - tests/**/*
