[metadata]
creation_date = "2020/09/01"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "ebe555d81187dfe879c5149586378c5400cd42e43e5f9c7f02b63bb71f8916f5"


[rule]
author = ["Elastic"]
description = """
Identifies when an Azure Conditional Access policy is modified. Azure Conditional Access policies control access to
resources via if-then statements. For example, if a user wants to access a resource, then they must complete an action
such as using multi-factor authentication to access it. An adversary may modify a Conditional Access policy in order to
weaken their target's security controls.
"""
from = "now-25m"
index = ["filebeat-*", "logs-azure*"]
language = "kuery"
license = "Elastic License"
name = "Azure Conditional Access Policy Modified"
note = "The Azure Filebeat module must be enabled to use this rule."
references = ["https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview"]
risk_score = 47
rule_id = "bc48bba7-4a23-4232-b551-eca3ca1e3f20"
severity = "medium"
tags = ["Elastic", "Cloud", "Azure", "Continuous Monitoring", "SecOps", "Configuration Audit"]
type = "query"

query = '''
event.dataset:(azure.activitylogs or azure.auditlogs) and ( azure.activitylogs.operation_name:"Update policy" or azure.auditlogs.operation_name:"Update policy" ) and event.outcome:(Success or success)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1098"
name = "Account Manipulation"
reference = "https://attack.mitre.org/techniques/T1098/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

