[metadata]
creation_date = "2024/05/02"
maturity = "production"
updated_date = "2024/05/02"
min_stack_comments = "ES|QL rule type is still in technical preview as of 8.13, however this rule was tested successfully; integration in tech preview"
min_stack_version = "8.13.0"

[rule]
author = ["Elastic"]
description = """
Identifies multiple violations of AWS Bedrock guardrails within a single response, increasing the likelihood of malicious
intent as well as the risk, since information was processed for return, before being prevented by the guardrail policy.
Multiple violations implies that a user may be intentionally attempting to cirvumvent security controls, access
sensitive information, or possibly exploit a vulnerability in the system.
"""
false_positives = ["Legitimate misunderstanding by users or overly strict policies"]
from = "now-60m"
interval = "10m"
language = "esql"
license = "Elastic License v2"
name = "AWS Bedrock Guardrails Detected Multiple Violations Within a Single Response"
references = [
    "https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-components.html",
    "https://atlas.mitre.org/techniques/AML.T0051",
    "https://atlas.mitre.org/techniques/AML.T0054",
]
risk_score = 73
rule_id = "17261da3-a6d0-463c-aac8-ea1718afcd20"
setup = """## Setup

This rule requires that guardrails are configured in AWS Bedrock. For more information, see the AWS Bedrock documentation:

https://docs.aws.amazon.com/bedrock/latest/userguide/guardrails-create.html
"""
severity = "high"
tags = [
    "Domain: LLM",
    "Data Source: AWS Bedrock",
    "Data Source: AWS S3",
    "Resources: Investigation Guide",
    "Use Case: Policy Violation",
    "Mitre Atlas: T0051",
    "Mitre Atlas: T0054",
]
timestamp_override = "event.ingested"
type = "esql"

query = '''
from logs-aws_bedrock.invocation-*
| where gen_ai.compliance.response_triggered is not null
| eval response_violations = mv_count(gen_ai.compliance.response_triggered)
| where response_violations > 1
| stats total_unique_response_violations = count(*) by response_violations, user.id, gen_ai.model.id, cloud.account.id
| sort total_unique_response_violations desc
'''
