# detection-rules config file

files:
  deprecated_rules: deprecated_rules.json
  packages: packages.yml
  stack_schema_map: stack-schema-map.yaml
  version_lock: version.lock.json


# to set up a custom rules directory, copy this file to the root of the custom rules directory, which is set
#   using the environment variable DETECTION_RULES_DIR
#   example structure:
#     custom-rules
#     ├── _config.yaml
#     ├── example_rule_1.toml
#     ├── example_rule_2.toml
#     └── etc
#         ├── deprecated_rules.json
#         ├── packages.yml
#         ├── stack-schema-map.yaml
#         └── version.lock.json
#
#   update custom-rules/_config.yaml with:
#     deprecated_rules: etc/deprecated_rules.json
#     packages: etc/packages.yml
#     stack_schema_map: etc/stack-schema-map.yaml
#     version_lock: etc/version.lock.json
#
#   the paths in this file are relative to the custom rules directory (DETECTION_RULES_DIR/)
#
# Refer to each original source file for purpose and proper formatting
#

# testing:
#  TBD...
