[metadata]
creation_date = "2021/01/11"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_rule_created_"
date = "2021/03/03"
pull_request = ""
sha256 = "f0cf0a445e6e685c307b59947b7ef8d2551dd03763193e5501cf5b575d932664"


[rule]
author = ["Elastic"]
description = """
Identifies the creation of a suspicious zip file prepended with special characters. Sandboxed Microsoft Office
applications on macOS are allowed to write files that start with special characters, which can be combined with an
AutoStart location to achieve sandbox evasion.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Potential Microsoft Office Sandbox Evasion"
references = [
    "https://i.blackhat.com/USA-20/Wednesday/us-20-Wardle-Office-Drama-On-macOS.pdf",
    "https://www.mdsec.co.uk/2018/08/escaping-the-sandbox-microsoft-office-on-macos/",
    "https://desi-jarvis.medium.com/office365-macos-sandbox-escape-fcce4fa4123c",
]
risk_score = 73
rule_id = "d22a85c6-d2ad-4cc4-bf7b-54787473669a"
severity = "high"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Defense Evasion"]
type = "query"

query = '''
event.category:file and not event.type:deletion and file.name:~$*.zip
'''

