[metadata]
creation_date = "2020/01/05"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_rule_created_"
date = "2021/03/03"
pull_request = ""
sha256 = "025a7961a346208d51c515719b4a7c881da666db7c3a17d3e012cad117b59e47"


[rule]
author = ["Elastic"]
description = """
Identifies attempts to add an account to the admin group via the command line. This could be an indication of privilege
escalation activity.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Potential Admin Group Account Addition"
references = ["https://managingosx.wordpress.com/2010/01/14/add-a-user-to-the-admin-group-via-command-line-3-0/"]
risk_score = 47
rule_id = "565c2b44-7a21-4818-955f-8d4737967d2e"
severity = "medium"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Privilege Escalation"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and process.name:(dscl or dseditgroup) and process.args:(("/Groups/admin" or admin) and ("-a" or "-append"))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1078"
name = "Valid Accounts"
reference = "https://attack.mitre.org/techniques/T1078/"
[[rule.threat.technique.subtechnique]]
id = "T1078.003"
name = "Local Accounts"
reference = "https://attack.mitre.org/techniques/T1078/003/"



[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"

