[metadata]
creation_date = "2020/09/03"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "701bb83db4ee9988f602d8483da8fd2616afd8d5182f6caba81a678824382d69"


[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
Looks for commands related to system process discovery from an unusual user context. This can be due to uncommon
troubleshooting activity or due to a compromised account. A compromised account may be used by a threat actor to engage
in system process discovery in order to increase their understanding of software applications running on a target host
or network. This may be a precursor to selection of a persistence mechanism or a method of privilege elevation.
"""
false_positives = [
    """
    Uncommon user command activity can be due to an engineer logging onto a server instance in order to perform manual
    troubleshooting or reconfiguration.
    """,
]
from = "now-45m"
interval = "15m"
license = "Elastic License"
machine_learning_job_id = "linux_system_process_discovery"
name = "Unusual Linux Process Discovery Activity"
risk_score = 21
rule_id = "5c983105-4681-46c3-9890-0c66d05e776b"
severity = "low"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "ML"]
type = "machine_learning"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1057"
name = "Process Discovery"
reference = "https://attack.mitre.org/techniques/T1057/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

