[metadata]
creation_date = "2020/03/25"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "bff9c2058c32e5568671a4de897f191a1a5fad599b2982f5f5c543d6a2dcb5df"


[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = "Identifies an unusually high number of authentication attempts."
false_positives = [
    """
    Security audits may trigger this alert. Conditions that generate bursts of failed logins, such as misconfigured
    applications or account lockouts could trigger this alert.
    """,
]
from = "now-45m"
interval = "15m"
license = "Elastic License"
machine_learning_job_id = "suspicious_login_activity_ecs"
name = "Unusual Login Activity"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
risk_score = 21
rule_id = "4330272b-9724-4bc6-a3ca-f1532b81e5c2"
severity = "low"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "ML"]
type = "machine_learning"

