[metadata]
creation_date = "2020/03/25"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "93b050224f92e0f3e5a043d6d2598a105fea78aebd8815f32e6932920731c7be"


[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = """
A machine learning job detected a PowerShell script with unusual data characteristics, such as obfuscation, that may be
a characteristic of malicious PowerShell script text blocks.
"""
false_positives = [
    """
    Certain kinds of security testing may trigger this alert. PowerShell scripts that use high levels of obfuscation or
    have unusual script block payloads may trigger this alert.
    """,
]
from = "now-45m"
interval = "15m"
license = "Elastic License"
machine_learning_job_id = "windows_anomalous_script"
name = "Suspicious Powershell Script"
references = ["https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html"]
risk_score = 21
rule_id = "1781d055-5c66-4adf-9d60-fc0fa58337b6"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "ML"]
type = "machine_learning"

