[metadata]
creation_date = "2020/09/22"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "12354ef075f45d594f81cd132ed6cd134dcd58e0e4181f55e2ca8fbab4ea1ca6"


[rule]
anomaly_threshold = 75
author = ["Elastic"]
description = """
Looks for anomalous access to the cloud platform metadata service by an unusual user. The metadata service may be
targeted in order to harvest credentials or user data scripts containing secrets.
"""
false_positives = [
    """
    A newly installed program, or one that runs under a new or rarely used user context, could trigger this detection
    rule. Manual interrogation of the metadata service during debugging or troubleshooting could trigger this rule.
    """,
]
from = "now-45m"
interval = "15m"
license = "Elastic License"
machine_learning_job_id = "windows_rare_metadata_user"
name = "Unusual Windows User Calling the Metadata Service"
risk_score = 21
rule_id = "df197323-72a8-46a9-a08e-3f5b04a4a97a"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "ML"]
type = "machine_learning"

