[metadata]
creation_date = "2020/09/02"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/09/02"

[rule]
author = ["Elastic"]
description = """
Identifies MsBuild.exe making outbound network connections. This may indicate adversarial activity as MsBuild is often
leveraged by adversaries to execute code and evade detection.
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*"]
language = "eql"
license = "Elastic License"
name = "MsBuild Making Network Connections: Sequence"
risk_score = 21
rule_id = "9dc6ed5d-62a9-4feb-a903-fafa1d33b8e9"
severity = "medium"
tags = ["Elastic", "Windows"]
type = "eql"

query = '''
sequence by process.entity_id, process.pid, process.name
  [process where event.type in ("start", "process_started") and process.name == "msbuild.exe"]
  [network where process.name == "msbuild.exe" and
     not (destination.address == "127.0.0.1" and source.address == "127.0.0.1")]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1127"
name = "Trusted Developer Utilities"
reference = "https://attack.mitre.org/techniques/T1127/"


[rule.threat.tactic]
id = "TA0010"
name = "Command and Control"
reference = "https://attack.mitre.org/tactics/TA0010/"
