[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "390f88f783c4f493a38b7d3c9b8ac6de3683336c9e7647c62c5656ecbf91b9c7"


[rule]
author = ["Elastic"]
description = """
Identifies use of the wbadmin.exe to delete the backup catalog. Ransomware and other malware may do this to prevent
system recovery.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "kuery"
license = "Elastic License"
name = "Deleting Backup Catalogs with Wbadmin"
risk_score = 21
rule_id = "581add16-df76-42bb-af8e-c979bfb39a59"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and process.name:wbadmin.exe and process.args:(catalog and delete)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1070"
name = "Indicator Removal on Host"
reference = "https://attack.mitre.org/techniques/T1070/"
[[rule.threat.technique.subtechnique]]
id = "T1070.004"
name = "File Deletion"
reference = "https://attack.mitre.org/techniques/T1070/004/"



[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

