[metadata]
creation_date = "2020/12/04"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "11237e7271d40e6753d629880da6f20a8a1a0a6b76236b6702308c5e6ded0e79"


[rule]
author = ["Elastic"]
description = """
Enumeration or discovery of the Windows registry using reg.exe. This information can be used to perform follow-on
activities.
"""
index = ["logs-endpoint.events.*", "winlogbeat-*", "logs-windows.*"]
language = "eql"
license = "Elastic License"
name = "Query Registry via reg.exe"
risk_score = 21
rule_id = "68113fdc-3105-4cdd-85bb-e643c416ef0b"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Discovery"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
  (process.name : "reg.exe" or process.pe.original_file_name == "reg.exe") and
  process.args == "query"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1012"
name = "Query Registry"
reference = "https://attack.mitre.org/techniques/T1012/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

