[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "1cae23e0af76735fbc7248df73a5ba48661f9c1aa7058e7a8fbdd3805ef93dc5"


[rule]
author = ["Elastic"]
description = """
Identifies use of whoami.exe which displays user, group, and privileges information for the user who is currently logged
on to the local system.
"""
false_positives = [
    """
    Some normal use of this program, at varying levels of frequency, may originate from scripts, automation tools and
    frameworks. Usage by non-engineers and ordinary users is unusual.
    """,
]
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "kuery"
license = "Elastic License"
name = "Whoami Process Activity"
risk_score = 21
rule_id = "ef862985-3f13-4262-a686-5f357bbb9bc2"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Discovery"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and process.name:whoami.exe
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1033"
name = "System Owner/User Discovery"
reference = "https://attack.mitre.org/techniques/T1033/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

