[metadata]
creation_date = "2020/12/04"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "e7600253fda0b1f4a313fe42fc2d80af2bd6f49573464d74777a86d8b83ca0ba"


[rule]
author = ["Elastic"]
description = """
Enumeration of files and directories using built-in tools. Adversaries may use the information discovered to plan
follow-on activity.
"""
index = ["logs-endpoint.events.*", "winlogbeat-*", "logs-windows.*"]
language = "eql"
license = "Elastic License"
name = "File and Directory Discovery"
risk_score = 21
rule_id = "7b08314d-47a0-4b71-ae4e-16544176924f"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Discovery"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
  (process.name : "cmd.exe" or process.pe.original_file_name == "Cmd.Exe") and
  process.args : ("dir", "tree")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1083"
name = "File and Directory Discovery"
reference = "https://attack.mitre.org/techniques/T1083/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

