[metadata]
creation_date = "2020/03/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "61548a211b657064f3f5fa31042085903bdfc11111e81e535b6a83efc90c195e"


[rule]
author = ["Elastic"]
description = """
Identifies the SYSTEM account using an account discovery utility. This could be a sign of discovery activity after an
adversary has achieved privilege escalation.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "kuery"
license = "Elastic License"
name = "Net command via SYSTEM account"
risk_score = 21
rule_id = "2856446a-34e6-435b-9fb5-f8f040bfa7ed"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Discovery"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and (process.name:(whoami.exe or net.exe) or process.name:net1.exe and not process.parent.name:net.exe) and user.name:SYSTEM
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1087"
name = "Account Discovery"
reference = "https://attack.mitre.org/techniques/T1087/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"

