[metadata]
creation_date = "2020/09/02"
ecs_version = ["1.6.0"]
maturity = "development"
updated_date = "2020/09/02"

[rule]
author = ["Elastic"]
description = """
Identifies .url shortcut files downloaded from outside the local network. These shortcut files are commonly used in
phishing campaigns.
"""
index = ["logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Downloaded URL Files"
risk_score = 21
rule_id = "cd82e3d6-1346-4afd-8f22-38388bbf34cb"
severity = "medium"
tags = ["from-eql-rules"]
type = "query"

query = '''
sequence by process.entity_id with maxspan=2s
  [file where event.type == "creation" and file.extension == "url" and
     not process.name == "explorer.exe"]
  [file where event.type == "creation" and file.extension == "url:Zone.Identifier" and
      // non-ECS field - may disqualify conversion
     file.Ext.windows.zone_identifier > 1 and not process.name == "explorer.exe"]
'''

