[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "0ce0903e91131f45212ff29c422ad14081e6226b5ef0dee0b3c18dc2f04fbee8"


[rule]
author = ["Elastic"]
description = """
Identifies use of the SysInternals tool PsExec.exe making a network connection. This could be an indication of lateral
movement.
"""
false_positives = [
    """
    PsExec is a dual-use tool that can be used for benign or malicious activity. It's important to baseline your
    environment to determine the amount of noise to expect from this tool.
    """,
]
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License"
name = "PsExec Network Connection"
risk_score = 21
rule_id = "55d551c6-333b-4665-ab7e-5d14a59715ce"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Execution"]
type = "eql"

query = '''
sequence by process.entity_id
  [process where process.name : "PsExec.exe" and event.type == "start"]
  [network where process.name : "PsExec.exe"]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1569"
name = "System Services"
reference = "https://attack.mitre.org/techniques/T1569/"
[[rule.threat.technique.subtechnique]]
id = "T1569.002"
name = "Service Execution"
reference = "https://attack.mitre.org/techniques/T1569/002/"



[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[rule.threat]]
framework = "MITRE ATT&CK"

[rule.threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"

