[metadata]
creation_date = "2020/11/15"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "6dc17115d6902e6b03a8faf85dcf8890314e600b12b78e4ad9950070c6829ae4"


[rule]
author = ["Elastic"]
description = """
Identifies process execution with a single character process name. This is often done by adversaries while staging or
executing temporary utilities.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License"
name = "Suspicious Execution - Short Program Name"
risk_score = 47
rule_id = "17c7f6a5-5bc9-4e1f-92bf-13632d24384d"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Execution"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and length(process.name) > 0 and
 length(process.name) == 5 and host.os.name == "Windows" and length(process.pe.original_file_name) > 5
'''

