[metadata]
creation_date = "2020/09/02"
ecs_version = ["1.6.0"]
maturity = "development"
updated_date = "2020/09/02"

[rule]
author = ["Elastic"]
description = """
Identifies InstallUtil.exe making outbound network connections. This may indicate adversarial activity as InstallUtil is
often leveraged by adversaries to execute code and evade detection.
"""
index = ["logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "InstallUtil Making Network Connections"
risk_score = 21
rule_id = "a13167f1-eec2-4015-9631-1fee60406dcf"
severity = "medium"
tags = ["from-eql-rules"]
type = "query"

query = '''
// this can be done without a sequence however, this does include more info on the process

sequence by process.entity_id
  [process where event.type in ("start", "process_started") and process.name == "installutil.exe"]
  [network where event.type == "connection" and network.direction == "outgoing"]
'''

