[metadata]
creation_date = "2020/09/02"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/09/02"

[rule]
author = ["Elastic"]
description = """
Identifies MsXsl.exe making outbound network connections. This may indicate adversarial activity as MsXsl is often
leveraged by adversaries to execute malicious scripts and evade detection.
"""
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "MsXsl Making Network Connections"
risk_score = 21
rule_id = "870d1753-1078-403e-92d4-735f142edcca"
severity = "medium"
tags = ["from-eql-rules"]
type = "eql"

query = '''
sequence by process.entity_id, process.pid, process.name
  [process where event.type in ("start", "process_started") and process.name == "msxsl.exe"]
  [network where event.type == "connection" and network.direction == "outgoing"]
'''

