[metadata]
creation_date = "2020/12/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_rule_created_"
date = "2021/03/03"
pull_request = ""
sha256 = "5b0ac663719faec8bf333e91683c3c8270c4b9616e5f728b8b626645d41a4d1a"


[rule]
author = ["Elastic"]
description = """
Identifies the creation of a hidden local user account by appending the dollar sign to the account name. This is
sometimes done by attackers to increase access to a system and avoid appearing in the results of accounts listing using
the net users command.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*", "logs-windows.*"]
language = "eql"
license = "Elastic License"
name = "Creation of a Hidden Local User Account"
references = [
    "https://blog.menasec.net/2019/02/threat-hunting-6-hiding-in-plain-sights_8.html",
    "https://github.com/CyberMonitor/APT_CyberCriminal_Campagin_Collections/tree/master/2020/2020.12.15.Lazarus_Campaign",
]
risk_score = 73
rule_id = "2edc8076-291e-41e9-81e4-e3fcbc97ae5e"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion", "Persistence"]
type = "eql"

query = '''
registry where registry.path : "HKLM\\SAM\\SAM\\Domains\\Account\\Users\\Names\\*$\\"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1136"
name = "Create Account"
reference = "https://attack.mitre.org/techniques/T1136/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

