[metadata]
creation_date = "2020/09/02"
ecs_version = ["1.6.0"]
maturity = "development"
updated_date = "2020/09/02"

[rule]
author = ["Elastic"]
description = """
Identifies probable exploitation of the Web Proxy Auto-Discovery Protocol (WPAD) service. Attackers who have access to
the local network or upstream DNS traffic can inject malicious JavaScript to the WPAD service which can lead to a full
system compromise.
"""
index = ["logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "WPAD Service Exploit"
risk_score = 21
rule_id = "ec328da1-d5df-482b-866c-4a435692b1f3"
severity = "high"
tags = ["from-eql-rules"]
type = "eql"

query = '''
sequence with maxspan=5s
  [process where event.type in ("start", "process_started") and process.name == "svchost.exe" and
     user.domain == "NT AUTHORITY" and user.name == "LOCAL SERVICE"] by process.entity_id
  [network where event.protocol == "dns" and
     dns.question.name == "wpad" and process.name == "svchost.exe"] by process.entity_id
  [network where event.type == "connection" and network.direction == "outgoing" and
     destination.port == 80 and process.name == "svchost.exe"] by process.entity_id
  [library where event.type == "start" and
     file.name == "jscript.dll" and process.name == "svchost.exe"] by process.entity_id
  [process where event.type in ("start", "process_started") and
     process.parent.name == "svchost.exe"] by process.parent.entity_id
'''

