[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "49bf69bac026013bdfd88dbb0ebbf5f2cf01d0bcc8dbdc00d760cc4c1ecf6daf"


[rule]
author = ["Elastic"]
description = """
Endpoint Security prevented Malware. Click the Endpoint Security icon in the event.module column or the link in the
rule.reference column for additional information.
"""
from = "now-15m"
index = ["endgame-*"]
interval = "10m"
language = "kuery"
license = "Elastic License"
name = "Malware - Prevented - Endpoint Security"
risk_score = 73
rule_id = "3b382770-efbb-44f4-beed-f5e0a051b895"
severity = "high"
tags = ["Elastic", "Endpoint Security"]
type = "query"

query = '''
event.kind:alert and event.module:endgame and endgame.metadata.type:prevention and (event.action:file_classification_event or endgame.event_subtype_full:file_classification_event)
'''

