[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "126b716fe963842ff8406842f8a101953a04e7e9f167e578094712fa6b006b00"


[rule]
author = ["Elastic"]
description = """
Endpoint Security detected Process Injection. Click the Endpoint Security icon in the event.module column or the link in
the rule.reference column for additional information.
"""
from = "now-15m"
index = ["endgame-*"]
interval = "10m"
language = "kuery"
license = "Elastic License"
name = "Process Injection - Detected - Endpoint Security"
risk_score = 73
rule_id = "80c52164-c82a-402c-9964-852533d58be1"
severity = "high"
tags = ["Elastic", "Endpoint Security"]
type = "query"

query = '''
event.kind:alert and event.module:endgame and endgame.metadata.type:detection and (event.action:kernel_shellcode_event or endgame.event_subtype_full:kernel_shellcode_event)
'''

