[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "bdc750ae44da6954d429af1c78db084f915fe63db463a2e084107bd4b7725a73"


[rule]
author = ["Elastic"]
description = """
Endpoint Security detected Credential Dumping. Click the Endpoint Security icon in the event.module column or the link
in the rule.reference column for additional information.
"""
from = "now-15m"
index = ["endgame-*"]
interval = "10m"
language = "kuery"
license = "Elastic License"
name = "Credential Dumping - Detected - Endpoint Security"
risk_score = 73
rule_id = "571afc56-5ed9-465d-a2a9-045f099f6e7e"
severity = "high"
tags = ["Elastic", "Endpoint Security"]
type = "query"

query = '''
event.kind:alert and event.module:endgame and endgame.metadata.type:detection and (event.action:cred_theft_event or endgame.event_subtype_full:cred_theft_event)
'''

