[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "60af511ccd3ed511fec254c879279d5090ca084efa9c11bc4fb01690450b7180"


[rule]
author = ["Elastic"]
description = """
Endpoint Security detected an Adversary Behavior. Click the Endpoint Security icon in the event.module column or the
link in the rule.reference column for additional information.
"""
from = "now-15m"
index = ["endgame-*"]
interval = "10m"
language = "kuery"
license = "Elastic License"
name = "Adversary Behavior - Detected - Endpoint Security"
risk_score = 47
rule_id = "77a3c3df-8ec4-4da4-b758-878f551dee69"
severity = "medium"
tags = ["Elastic", "Endpoint Security"]
type = "query"

query = '''
event.kind:alert and event.module:endgame and (event.action:rules_engine_event or endgame.event_subtype_full:rules_engine_event)
'''

