[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "ddc7ab73355be41f897b01ef0179d7f2e122f9e5e080842130db2d08cc80a7f7"


[rule]
author = ["Elastic"]
description = """
A request to web application returned a 405 response which indicates the web application declined to process the request
because the HTTP method is not allowed for the resource
"""
false_positives = [
    """
    Security scans and tests may result in these errors. Misconfigured or buggy applications may produce large numbers
    of these errors. If the source is unexpected, the user unauthorized, or the request unusual, these may indicate
    suspicious or malicious activity.
    """,
]
index = ["apm-*-transaction*"]
language = "kuery"
license = "Elastic License"
name = "Web Application Suspicious Activity: Unauthorized Method"
references = ["https://en.wikipedia.org/wiki/HTTP_405"]
risk_score = 47
rule_id = "75ee75d8-c180-481c-ba88-ee50129a6aef"
severity = "medium"
tags = ["Elastic", "APM"]
type = "query"

query = '''
http.response.status_code:405
'''

