[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "ee161dc933e878f4bc4cf1268c27f492ba323af6f082fe0b89d7385c31ef1b4e"


[rule]
author = ["Elastic"]
description = """
This is an example of how to detect an unwanted web client user agent. This search matches the user agent for sqlmap
1.3.11, which is a popular FOSS tool for testing web applications for SQL injection vulnerabilities.
"""
false_positives = [
    """
    This rule does not indicate that a SQL injection attack occurred, only that the `sqlmap` tool was used. Security
    scans and tests may result in these errors. If the source is not an authorized security tester, this is generally
    suspicious or malicious activity.
    """,
]
index = ["apm-*-transaction*"]
language = "kuery"
license = "Elastic License"
name = "Web Application Suspicious Activity: sqlmap User Agent"
references = ["http://sqlmap.org/"]
risk_score = 47
rule_id = "d49cc73f-7a16-4def-89ce-9fc7127d7820"
severity = "medium"
tags = ["Elastic", "APM"]
type = "query"

query = '''
user_agent.original:"sqlmap/1.3.11#stable (http://sqlmap.org)"
'''

