[metadata]
creation_date = "2020/11/03"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "036f3e7f9be396c953172509a4a62dfecbb5652ebafc6372c1dd982f724d9a28"


[rule]
author = ["Elastic"]
description = """
Timestomping is an anti-forensics technique which is used to modify the timestamps of a file, often to mimic files that
are in the same folder.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
max_signals = 33
name = "Timestomping using Touch Command"
risk_score = 47
rule_id = "b0046934-486e-462f-9487-0d4cf9e429c6"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "macOS", "Threat Detection", "Defense Evasion"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
 process.name : "touch" and process.args : ("-r", "-t", "-a*","-m*")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1070"
name = "Indicator Removal on Host"
reference = "https://attack.mitre.org/techniques/T1070/"
[[rule.threat.technique.subtechnique]]
id = "T1070.006"
name = "Timestomp"
reference = "https://attack.mitre.org/techniques/T1070/006/"



[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

