[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "341cfdb6003ebe2e04d21cabf87e4b10d70a4e08cb13c761d0a908c5a32b5b23"


[rule]
author = ["Elastic"]
description = "Identifies processes running in a temporary folder. This is sometimes done by adversaries to hide malware."
false_positives = [
    """
    Build systems, like Jenkins, may start processes in the `/tmp` directory. These can be exempted by name or by
    username.
    """,
]
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Unusual Process Execution - Temp"
risk_score = 47
rule_id = "df959768-b0c9-4d45-988c-5606a2be8e5a"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "Threat Detection"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and process.working_directory:/tmp
'''

