[metadata]
creation_date = "2020/02/18"
maturity = "production"
minimum_kibana_version = "7.13"
updated_date = "2021/03/03"
[[metadata.changelog]]
message = "_version_locked_"
date = "2021/03/03"
pull_request = ""
sha256 = "5a2e01d58289f281749c117a835f976958732477825b70a6bcfc4752d0327947"


[rule]
author = ["Elastic"]
description = """
Hping ran on a Linux host. Hping is a FOSS command-line packet analyzer and has the ability to construct network packets
for a wide variety of network security testing applications, including scanning and firewall auditing.
"""
false_positives = [
    """
    Normal use of hping is uncommon apart from security testing and research. Use by non-security engineers is very
    uncommon.
    """,
]
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Hping Process Activity"
references = ["https://en.wikipedia.org/wiki/Hping"]
risk_score = 73
rule_id = "90169566-2260-4824-b8e4-8615c3b4ed52"
severity = "high"
tags = ["Elastic", "Host", "Linux", "Threat Detection"]
type = "query"

query = '''
event.category:process and event.type:(start or process_started) and process.name:(hping or hping2 or hping3)
'''

