name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: membership
        uses: actions/github-script@v4
        id: mem
        with:
          github-token: ${{ secrets.READ_ORG_TOKEN }}
          script: |
            return github.orgs.getMembershipForAuthenticatedUser({
                org: "elastic",
                username: context.payload.sender.login
              })
      - name: Add community label if not member of Elastic org
        uses: actions/github-script@v4
        if: |
          "${{steps.mem.outputs.result}}" == "active"
        with:
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['elasticMember']
            })
