name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      github.orgs.getMembershipForAuthenticatedUser({org: "elastic", username: context.payload.sender.login}).state == "active"
    steps:
      - name: membership
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.READ_ORG_TOKEN }}
          script: |
            echo "No label needed"
      - name: Get result
        run: echo "${{steps.mem.outputs.result}}"
