name: View context attributes
on:
  *

jobs:
  test:
    uses: actions/github-script@v4
    with:
      script: |
        console.log(context)
        console.log(
          github.orgs.getMembershipForUser({
            org: elastic,
            user: context.actor
          })
        )
