name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    steps:
      - name: membership
        runs-on: ubuntu-latest
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            console.log(
              github.orgs.getMembershipForUser({
                org: elastic,
                user: context.actor
              })
            )
