name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: membership
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context)
            console.log(github.orgs.getMembershipForAuthenticatedUser({
                org: "elastic",
                username: context.payload.sender.login
              }))
