name: test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: membership
        uses: actions/github-script@v4
        id: membership
        with:
          github-token: ${{ secrets.READ_ORG_TOKEN }}
          script: |
            # console.log(context)
            return github.orgs.getMembershipForAuthenticatedUser({
                org: "elastic",
                username: context.payload.sender.login
              })
